USE [ShortenURLDB]
GO


SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[URL](
	[ID] [BigInt] IDENTITY(1,1) NOT NULL,
	[url] [varchar](Max) NOT NULL,
	[HashValue] [varchar](128) NOT NULL,
 CONSTRAINT [PK_Collection] PRIMARY KEY CLUSTERED 
(
	[HashValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

USE [ShortenURLDB]
GO